### ISSUE TITLE
[Feature Request] Dark mode on documentation.

### ISSUE THREAD

**Issue by anthony0030** [jackocnr/intl-tel-input#1588]
I can't find the code for the documentation, BUT here is a suggestion to reduce eye pain when reading documentation.

``` CSS

/* SPF 50+ for dark mode users */
@media (prefers-color-scheme: dark) {
  :root {
    --bs-body-bg: var(--bs-dark);
    --bs-body-color: var(--bs-light);
    --bs-code-color: #FF99CC;
    --bs-link-color: #60A0FF;
    --bs-link-hover-color: #A0C7FF;
  }
}

/* As navlink color is hardcoded */
.iti-sidebar .nav-link {
  color: var(--bs-body-color);
}

/* As the input inherits the text color, possible bug */
.iti {
  color:  var(--bs-dark);
}

```

If I knew how to contribute to the documentation code I would make this as a pull request.
