### ISSUE TITLE
Compatibility with Bootstrap 4 form-control css class

### ISSUE THREAD

**Issue by D4rkTiger** [jackocnr/intl-tel-input#948]
Hi,

Due to transformation of input by JS, the created container needs to support the additional CSS class `.form-control if we integrate the input in a **Bootstrap 4 form**.

```javascript
window.intlTelInput(document.querySelector("input[type='tel']"),
    {
        customContainer: "form-control"
    }
);
```

So to be compatible with, the class `.iti` just needs to cancel padding when it is couple with `.form-control`

The SCSS code part
```scss
.iti {
  //Use for compatibility with Bootstrap 4
  &.form-control {
      padding: 0;
  }
}
```
